version: '3.4'

services:
  mottadevelopments.chatroom.identity.api:
    container_name: mottadevelopments-chatroom-identity
    image: ${DOCKER_REGISTRY-}mottadevelopmentschatroomidentityapi
    build:
      context: .
      dockerfile: src/identity/MottaDevelopments.ChatRoom.Api/Dockerfile
    depends_on:
      - sqlserver

  mottadevelopments.chatroom.gateway:
    container_name: mottadevelopments-chatroom-gateway
    image: ${DOCKER_REGISTRY-}mottadevelopmentschatroomgateway
    build:
      context: .
      dockerfile: src/gateway/MottaDevelopments.ChatRoom.Gateway/Dockerfile
 
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
  
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu